@startuml GameFlow
start
:Choose game configuration;
repeat :Upgrade phase;
    if (Upgrades bought) then (True)
        :Save upgrade cards;
    endif
    :Programming phase;
    :Draw cards;
    :Program robot;
    :Activation phase;
    repeat :Play current register;
    :Board elements;
    backward :Increment register;
    repeat while (Current register < 5) is (True)
repeat while (Winner found) is (False) not (True)
stop
@enduml